# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0003_auto_20200820_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retentionpolicyitem',
            old_name='start_date',
            new_name='start_date_time',
        ),
    ]
