# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0003_auto_20200820_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetentionPolicyItem',
        ),
    ]
