# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0004_auto_20200825_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetentionPolicyItem',
        ),
    ]
